package com.app.entity;

public enum CurrentStatus {
    SCREEN_SELECTED,
    SCREEN_REJECTED,
    SCREEN_PENDING,
    MCQ_SELECTED,
    MCQ_REJECTED,
    MCQ_SCHEDULED,
    INTERVIEW_SCHEDULED,
    INTERVIEW_PENDING,
    INTERVIEW_SELECTED,
    INTERVIEW_REJECTED
}